version: '3.1'

services:
  joomla:
    build: .
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
      - 9001:9001
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
    volumes:
      - type: bind
        source: ./web
        target: /var/www/html

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1